### PR TITLE
fix selection of overlapped rect and path

### LINKED ISSUE #121: PDF Annotation Tool bug - drawn z-indexes selection
Identify which [thing] is being dragged, aka. Z index of drawn thingies

### PR DESCRIPTION
**Pull request by fannydengdeng**
closes https://github.com/rezqio/issues/issues/121

ff results in the same behavior but it has another issue with annotation selection only being responsive on the textLayer, can investigate in a future PR

### CODE REVIEW

File: src/UI/utils.js [hunk 1]
```diff
@@ -65,11 +67,40 @@ export function findSVGAtPoint(x, y) {
...
   if (!svg) { return; }
+
+  // temporarily disable pointer events on textLayer
+  document.getElementsByClassName('textLayer')[0].style.pointerEvents = "none";
+
+  // Find rectangle/lines annotations
+  for (let xTest = x - HIT_TEST_OFFSET; xTest <= x + HIT_TEST_OFFSET; xTest++) {
+    for (let yTest = y - HIT_TEST_OFFSET; yTest <= y + HIT_TEST_OFFSET; yTest++) {
+      let candidate = document.elementFromPoint(xTest, yTest);
+      if (candidate) {
```
Comment (dongyuzheng) [inline src/UI/utils.js]: Can we unnest these ifs into if guards (continue) statements?

e.g.,

`if (!candidate) { continue; }`

**Review by dongyuzheng — APPROVED** [review]
LGTM except nested ifs
